In [1]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
import numpy as np

from tensorflow.python.keras._impl.keras.datasets.cifar10 import load_data

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
def next_batch(num, data, labels):
    
    idx = np.arange(0 , len(data))
    np.random.shuffle(idx)
    idx = idx[:num]
    data_shuffle = [data[ i] for i in idx]
    labels_shuffle = [labels[ i] for i in idx]

    return np.asarray(data_shuffle), np.asarray(labels_shuffle)

(x_train, y_train), (x_test, y_test) = load_data()
y_train_one_hot = tf.squeeze(tf.one_hot(y_train, 10),axis=1)
y_test_one_hot = tf.squeeze(tf.one_hot(y_test, 10),axis=1)

In [3]:
x = tf.placeholder(tf.float32, [None, 32, 32, 3])

In [4]:
config = tf.ConfigProto()
config.gpu_options.allow_growth = True

sess = tf.Session(config=config)

sess.run(tf.global_variables_initializer())

batch = next_batch(128, x_train, y_train_one_hot.eval(session=sess))

In [5]:
gather = tf.gather(tf.gather(x, 0),1)
test1 = sess.run(gather, feed_dict={x:batch[0]})
print(test1.shape)

(32, 3)


In [6]:
def getzero(trans_mat, indices_mat, keep_prob):
    last_shape = trans_mat.shape[1]
    live_shape = last_shape*keep_prob
    
    #print(trans_mat.shape)
    mul_mat = []
    #print(trans_mat.shape)
    #print(indices_mat.shape)
    #print(trans_mat.shape[1])
    for i in range(trans_mat.shape[0]):
        save_list = []
        for j in range(trans_mat.shape[1]):
            if indices_mat[i][j] > live_shape:
                save_list.append(np.zeros_like(trans_mat[0][0]))
                
            else:
                save_list.append(np.ones_like(trans_mat[0][0]))
                
        print(save_list)
        mul_mat.append(np.array(save_list))
    #print(mul_mat)
    mul_mat = np.array(mul_mat)            
    return mul_mat

sum_mat1 = tf.reduce_sum(tf.reduce_sum(x, axis=1), axis=1)
_, indices1 = tf.nn.top_k(sum_mat1, k=sum_mat1.shape[1])
x_pool2_trans = tf.transpose(x, perm=[0,3,1,2])
one_zero1 = tf.py_func(getzero, [x_pool2_trans, indices1, 0.5], tf.float32)
mul_trans1 = tf.transpose(one_zero1, perm=[0,2,3,1])

test = sess.run(mul_trans1, feed_dict={x:batch[0]})

[array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32), array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32), array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)]
[array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 

       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)]
[array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32), array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32), array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)]
[array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [

[array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32), array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32), array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)]
[array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 

In [7]:
def getzero(trans_mat, indices_mat, keep_prob):
    last_shape = trans_mat.shape[1]
    live_shape = last_shape*keep_prob
    
    mul_mat = []
    
    for i in range(trans_mat.shape[0]):
        for j in range(trans_mat.shape[1]):
            if indices_mat[i][j] > live_shape:
                mul_mat.append(np.zeros_like(trans_mat[0][0]))
                
            else:
                mul_mat.append(np.ones_like(trans_mat[0][0]))
    mul_mat = np.array(mul_mat)            
    return mul_mat
    
def selout(mat, keep_prob, axis=3, session=sess):
    #return tf.nn.top_k(mat,k=4, sorted=True)
    trans_mat = tf.transpose(mat, perm=[0,3,1,2])
    print(trans_mat.shape[1])
#    trans_mat = tf.reshape(mat, [-1, mat.shape[3], mat.shape[1], mat.shape[2]])
    last_shape = tf.cast(tf.shape(trans_mat)[1], dtype=tf.float32)
    live_shape = tf.cast(last_shape*keep_prob, dtype=tf.int32)
    sum_mat = tf.reduce_sum(tf.reduce_sum(trans_mat, axis=2), axis=2)
    
    _, indices_mat = tf.nn.top_k(sum_mat, k=trans_mat.shape[1])
    tf.py_func
    
    return live_mat
    live_mat = trans_mat[top_mat.indices[0], top_mat.indices[1]]
    zero_mat = tf.zeros_like(mat[:,:,:,:tf.cast(last_shape, dtype=tf.int32) - live_shape], dtype=tf.float32)
    result_mat = tf.concat([live_mat.values, zero_mat], axis=axis)
    
    result_transpose_mat = tf.transpose(result_mat, perm=[0,2,3,1])
    
    return sum_mat

x_trans = tf.transpose(x, perm=[0,3,1,2])
sum_mat = tf.reduce_sum(tf.reduce_sum(x_trans, axis=2), axis=2)
_, indices = tf.nn.top_k(sum_mat, k=sum_mat.shape[1])
sel_tf = tf.py_func(getzero, [x_trans, indices, 0.5], tf.float32)
test = sess.run(sel_tf, feed_dict={x:batch[0]})
print(test)

[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [8]:
keep_prob = 0.5
#합에 따라 정렬
def sorted_sum(arr, sess=sess):
    with gpu(0):
        print(arr.shape)
        result_list = []
        print(result_list)
        for i in range(arr.shape[0]):
            reduce_sum = mnp.sum(np.sum(arr[i], axis=1),axis=1)
            arg_list = mnp.argsort(reduce_sum)
            arr_list = mnp.sort(arr[i], axis=0)[arg_list,:,:]
            result_list.append(np.sort(arr[i]))
        result_list = mnp.array(result_list)
        print(result_list.shape[1])
        result_list[:,int(keep_prob*result_list.shape[1]+0.5):] = 0
        print(result_list.shape)
        return result_list

test = sess.run(tf.transpose(x, perm=[0,3,1,2]), feed_dict={x:batch[0]})
sorted1 = tf.py_func(sorted_sum, [x], tf.float32)
print(sorted1.eval(session=sess, feed_dict={x:batch[0]})[0])

UnknownError: NameError: name 'gpu' is not defined
	 [[Node: PyFunc_2 = PyFunc[Tin=[DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_0_0)]]

Caused by op 'PyFunc_2', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-cb0661f7640f>", line 20, in <module>
    sorted1 = tf.py_func(sorted_sum, [x], tf.float32)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 212, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_script_ops.py", line 50, in _py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/jsc5565/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnknownError (see above for traceback): NameError: name 'gpu' is not defined
	 [[Node: PyFunc_2 = PyFunc[Tin=[DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_0_0)]]


In [ ]:

"""
#print(tf.nn.top_k(tf.reduce_sum(tf.reduce_sum(batch[0], axis=1), axis=1), k=3).indices.eval(session=sess))
expand = tf.expand_dims(tf.nn.top_k(tf.reduce_sum(tf.reduce_sum(x, axis=1), axis=1), k=3).indices, axis=-1)
reordered = tf.gather_nd(tf.transpose(x, perm=[0,3,1,2]), expand)
print(tf.reduce_sum(tf.reduce_sum(x, axis=1), axis=1).shape)
print(tf.transpose(x, perm=[0,3,1,2]).shape)
print(expand.shape)
print(reordered.shape)
"""

In [ ]:
#print(tf.nn.top_k(tf.reduce_sum(tf.reduce_sum(x, axis=1), axis=1).eval(session=sess, feed_dict={x:batch[0]})).values)
print(reordered.eval(session=sess, feed_dict={x:batch[0]})[y0])


In [ ]:
print(reordered.eval(session=sess, feed_dict={x:batch[0]})[::2].shape)
print(reordered.eval(session=sess, feed_dict={x:batch[0]})[2] == reordered.eval(session=sess, feed_dict={x:batch[0]})[3] )

In [ ]:
sum = tf.nn.top_k(tf.reduce_sum(tf.reduce_sum(x, axis=1), axis=1), k=3)
print(sess.run(sum, feed_dict={x:batch[0]}).indices)

In [ ]:
count = 0
for i in range(64):
    for j in range(64):
        if (reordered.eval(session=sess, feed_dict={x:batch[0]})[i] == reordered.eval(session=sess, feed_dict={x:batch[0]})[j]).all():
            if not(i==j):
           #     print(i,j)
                count += 1
print(count/2)
#    print(reordered.eval(session=sess, feed_dict={x:batch[0]})[::2,0,0,] == reordered.eval(session=sess, feed_dict={x:batch[0]})[::2,0,0,1])

In [ ]:
#print(reordered.eval(session=sess, feed_dict={x:batch[0]})[0])
print(3*3*32*32/3)

In [ ]:
print(reordered.eval(session=sess, feed_dict={x:batch[0]})[::2].shape)

In [ ]:
x = tf.Variable([])

In [ ]:
for i in range(10):
    y = tf.Variable([])
    for j in range(10):
        z = tf.Variable([j], dtype=tf.float32)
        y = tf.concat([y, z], axis=0)
        print(y.shape)